name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # Build App
  build:
    runs-on: windows-latest
    
    env:
      SCHEDULER_APP_KEY: ${{ secrets.SCHEDULER_APP_KEY }}
      SCHEDULER_APP_MSAL_KEY: ${{ secrets.SCHEDULER_APP_MSAL_KEY }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.0        

      - name: Build SchedulerApp Solution
        run: msbuild ./SchedulerApp.sln /restore /p:Configuration=Release

      - name: Create and Sign the APK
        run: msbuild SchedulerApp\SchedulerApp.Android\SchedulerApp.Android.csproj /t:SignAndroidPackage /p:Configuration=Release /p:OutputPath=bin\Release\

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: SchedulerApp.apk
          path: SchedulerApp\SchedulerApp.Android\bin\Release\es.unicosgaming.schedulerapp-Signed.apk 

